
spring:
  config:
    import: optional:configserver:http://localhost:8888
    activate:
      on-profile: dev
  cloud:
    config:
      overrideNone: true
      uri: http://localhost:8888
      name: virtual-backend
      enabled: false
      profile: dev

#test:
#  property: 2
