services:
  postgres-demo:
    container_name: postgres-demo
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=demo'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    volumes:
      - ./local/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - '7432:5432'
    networks:
      - demo
networks:
  demo:
    driver: bridge
    name: demo